---
- name: Patch OS
  hosts: all
  tasks:

    - name: Register nodes to Redhat
      community.general.redhat_subscription:
        state: present
        username: eanning10
        password: Jennelle65493705!
        auto_attach: true 

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
  
    